apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vault.fullname" . }}-config
  labels:
    {{- include "vault.labels" . | nindent 4 }}
data:
  config.hcl: |
    ui = {{ .Values.config.ui }}

    listener "tcp" {
      address         = "{{ .Values.config.listener.address }}"
      cluster_address = "{{ .Values.config.listener.clusterAddress }}"
      tls_disable     = {{ ternary 1 0 .Values.config.listener.tlsDisable }}
    }

    storage "file" {
      path = "{{ .Values.config.storage.path }}"
    }

    api_addr = "{{ .Values.config.apiAddr }}"

    disable_mlock = {{ .Values.config.disableMlock }}

    default_lease_ttl = "{{ .Values.config.defaultLeaseTtl }}"
    max_lease_ttl     = "{{ .Values.config.maxLeaseTtl }}"

    log_level  = "{{ .Values.config.logLevel }}"
    log_format = "{{ .Values.config.logFormat }}"
