replicaCount: 1

image:
  repository: hashicorp/vault
  tag: "1.21.3"
  pullPolicy: IfNotPresent

vault:
  addr: "http://0.0.0.0:8200"
  skipVerifyConfigPermissions: "true"

config:
  ui: false
  apiAddr: "http://vault-vault:8200"

  listener:
    address: "0.0.0.0:8200"
    clusterAddress: "0.0.0.0:8201"
    tlsDisable: true

  storage:
    path: "/vault/file"

  disableMlock: true
  defaultLeaseTtl: "168h"
  maxLeaseTtl: "720h"
  logLevel: "info"
  logFormat: "json"

service:
  type: ClusterIP
  port: 8200
  clusterPort: 8201

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi
  storageClassName: ""

logs:
  enabled: true

ingress:
  enabled: false
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  host: vault.example.internal
  path: /
  pathType: Prefix

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

initJob:
  enabled: false

bootstrapJob:
  enabled: true

  image:
    repository: hashicorp/vault
    tag: "1.21.3"
    pullPolicy: IfNotPresent

  vaultAddr: "http://vault-vault:8200"

  bootstrapStorage:
    size: 1Gi
    accessMode: ReadWriteOnce
    storageClassName: ""

  agentCredentialsStorage:
    size: 1Gi
    accessMode: ReadWriteOnce
    storageClassName: ""

  resources: {}

agentCleaner:
  enabled: true

  image:
    repository: hashicorp/vault
    tag: "1.21.3"
    pullPolicy: IfNotPresent

  vaultAddr: "http://vault-vault:8200"
  logLevel: info

  roleName: cleaner
  roleIdFile: /agent/credentials/cleaner_role_id
  secretIdFile: /agent/credentials/cleaner_secret_id
  tokenFile: /agent/out/token

  resources: {}
