replicaCount: 1

image:
  repository: hashicorp/vault
  tag: "1.21.3"
  pullPolicy: IfNotPresent

vault:
  addr: "http://0.0.0.0:8200"
  skipVerifyConfigPermissions: "true"

config:
  ui: true
  listener:
    address: "0.0.0.0:8200"
    clusterAddress: "0.0.0.0:8201"
    tlsDisable: true
  storage:
    path: "/vault/file"
  disableMlock: true

service:
  type: ClusterIP
  port: 8200
  clusterPort: 8201

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi
  storageClassName: ""

logs:
  enabled: true

** Ingress tühjaks jätta, ei tohiks vajalik olla aga jätan võimaluse sisse
ingress:
  enabled: false
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  host: vault
  path: /
  pathType: Prefix

initJob:
  enabled: true

  image:
    repository: hashicorp/vault
    tag: "1.21.3"
    pullPolicy: IfNotPresent

  vaultAddr: "http://vault-vault:8200"

  backoffLimit: 1

  wait:
    enabled: true
    retries: 60
    sleepSeconds: 5

  init:
    keyShares: 5
    keyThreshold: 3

  output:
    mode: stdout
    secretName: vault-init-output

  resources: {}
  
bootstrapJob:
  enabled: true

  image:
    repository: hashicorp/vault
    tag: "1.21.3"
    pullPolicy: IfNotPresent

  vaultAddr: "http://vault-vault:8200"

  bootstrapStorage:
    size: 1Gi
    accessMode: ReadWriteOnce
    storageClassName: ""

  agentCredentialsStorage:
    size: 1Gi
    accessMode: ReadWriteOnce
    storageClassName: ""

  agentTokenStorage:
    enabled: false
    size: 1Gi
    accessMode: ReadWriteOnce
    storageClassName: ""

  resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
