apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.nfs.backendPvcName }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.nfs.storageClass }}
  resources:
    requests:
      storage: {{ .Values.nfs.storageSize }}
