# Rakenduse, ntx Ruuteri PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.nfs.pvName }}
spec:
  capacity:
    storage: {{ .Values.nfs.storageSize }}
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.nfs.serviceName }}.{{ .Values.namespace }}.svc.cluster.local
    path: {{ .Values.nfs.nfsPath }}
  persistentVolumeReclaimPolicy: Retain
