apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nfs.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  selector:
    app: nfs-server
  ports:
  - name: nfs
    port: 2049
    targetPort: 2049
